-- MySQL Script generated by MySQL Workbench
-- Thu Nov 23 12:42:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `registration_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`playlists` ;

CREATE TABLE IF NOT EXISTS `mydb`.`playlists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `description` TEXT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_playlists_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_playlist_unique` (`id` ASC, `user_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`podcasts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`podcasts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`podcasts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `description` TEXT NULL,
  `rss_feed` VARCHAR(2000) NOT NULL,
  `image` VARCHAR(2000) NOT NULL,
  `author` VARCHAR(200) NOT NULL,
  `episodes_count` MEDIUMINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rss_feed_UNIQUE` (`rss_feed` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`episodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`episodes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`episodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  `description` TEXT NULL,
  `duration` INT NOT NULL,
  `released_at` DATETIME NOT NULL,
  `audio_url` VARCHAR(2000) NOT NULL,
  `podcast_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `audio_url_UNIQUE` (`audio_url` ASC) VISIBLE,
  INDEX `fk_episodes_podcasts_idx` (`podcast_id` ASC) VISIBLE,
  CONSTRAINT `fk_episodes_podcasts`
    FOREIGN KEY (`podcast_id`)
    REFERENCES `mydb`.`podcasts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorize` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorize` (
  `podcast_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`podcast_id`, `category_id`),
  INDEX `fk_podcasts_has_categories_categories1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_podcasts_has_categories_podcasts1_idx` (`podcast_id` ASC) VISIBLE,
  CONSTRAINT `fk_podcasts_has_categories_podcasts1`
    FOREIGN KEY (`podcast_id`)
    REFERENCES `mydb`.`podcasts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_podcasts_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`queue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`queue` ;

CREATE TABLE IF NOT EXISTS `mydb`.`queue` (
  `episode_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `index` SMALLINT NULL,
  PRIMARY KEY (`episode_id`, `user_id`),
  INDEX `fk_episodes_has_users_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_episodes_has_users_episodes1_idx` (`episode_id` ASC) VISIBLE,
  CONSTRAINT `fk_episodes_has_users_episodes1`
    FOREIGN KEY (`episode_id`)
    REFERENCES `mydb`.`episodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_episodes_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`listen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`listen` (
  `episode_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `progression` INT NOT NULL,
  `listening_count` TINYINT NULL,
  PRIMARY KEY (`episode_id`, `user_id`),
  INDEX `fk_episodes_has_users_users2_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_episodes_has_users_episodes2_idx` (`episode_id` ASC) VISIBLE,
  CONSTRAINT `fk_episodes_has_users_episodes2`
    FOREIGN KEY (`episode_id`)
    REFERENCES `mydb`.`episodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_episodes_has_users_users2`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`list` ;

CREATE TABLE IF NOT EXISTS `mydb`.`list` (
  `playlist_id` INT NOT NULL,
  `episode_id` INT NOT NULL,
  PRIMARY KEY (`playlist_id`, `episode_id`),
  INDEX `fk_playlists_has_episodes_episodes1_idx` (`episode_id` ASC) VISIBLE,
  INDEX `fk_playlists_has_episodes_playlists1_idx` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_has_episodes_playlists1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `mydb`.`playlists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlists_has_episodes_episodes1`
    FOREIGN KEY (`episode_id`)
    REFERENCES `mydb`.`episodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `note` TINYINT NOT NULL,
  `content` TEXT NULL,
  `date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `parent_id` INT NULL,
  `episode_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `parent_id`, `episode_id`),
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_comments1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_comments_episodes1_idx` (`episode_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_episodes1`
    FOREIGN KEY (`episode_id`)
    REFERENCES `mydb`.`episodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`badges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`badges` ;

CREATE TABLE IF NOT EXISTS `mydb`.`badges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `points` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `type` TINYINT NOT NULL,
  `condition_value` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obtain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`obtain` ;

CREATE TABLE IF NOT EXISTS `mydb`.`obtain` (
  `badge_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`badge_id`, `user_id`),
  INDEX `fk_badges_has_users_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_badges_has_users_badges1_idx` (`badge_id` ASC) VISIBLE,
  CONSTRAINT `fk_badges_has_users_badges1`
    FOREIGN KEY (`badge_id`)
    REFERENCES `mydb`.`badges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_badges_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
