/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package podweb;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import io.javalin.Javalin;
import io.javalin.testtools.JavalinTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class AppTest {

	static Javalin app = App.setupApp();

	@BeforeAll
	public static void setup() {
		app.start();
	}

	@AfterAll
	public static void tearDown() {
		app.stop();
	}

	@Test
	public void home_page_returns_welcome_message() {
		JavalinTest.test(app, (server, client) -> {
			var res = client.get("/");
			assertEquals(200, res.code());
			assertEquals("Welcome on Podweb", res.body().string());
		});
	}

}