/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package podweb;

import io.javalin.Javalin;

public class App {
	static final int PORT = 7000;
	static Javalin app;

	public static void main(String[] args) {
		System.out.println("Podweb server has started...");
		app = setupApp().start(PORT);
	}

	// Separated method to easily test the server
	public static Javalin setupApp() {
		Javalin app = Javalin.create();
		// TODO: Defines routes
		app.get("/", ctx -> ctx.render("layout.jte"));
		return app;
	}
}
